// <auto-generated />
using System;
using CursorWebAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CursorWebAPI.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CursorWebAPI.Domain.Show", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FunFact")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ShowDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("YouTubeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShowDate");

                    b.ToTable("Shows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Ithaca",
                            FunFact = "Widely considered one of the greatest Grateful Dead concerts ever performed. The tape circulated for decades as a legendary bootleg.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Barton_Hall_Cornell.jpg/800px-Barton_Hall_Cornell.jpg",
                            ShowDate = new DateOnly(1977, 5, 8),
                            State = "NY",
                            Venue = "Barton Hall, Cornell University",
                            YouTubeUrl = "https://www.youtube.com/watch?v=jLGk3CVMdQU"
                        },
                        new
                        {
                            Id = 2,
                            City = "Veneta",
                            FunFact = "The iconic \"Sunshine Daydream\" show—famous for its high energy and the psychedelic film footage from the day.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Veneta%2C_Oregon.jpg/800px-Veneta%2C_Oregon.jpg",
                            ShowDate = new DateOnly(1972, 8, 27),
                            State = "OR",
                            Venue = "Old Renaissance Faire Grounds",
                            YouTubeUrl = "https://www.youtube.com/watch?v=JidgG6g1l3o"
                        },
                        new
                        {
                            Id = 3,
                            City = "Philadelphia",
                            FunFact = "A massive summer '89 stadium performance—often cited as a peak era for the band's late-career sound.",
                            ShowDate = new DateOnly(1989, 7, 7),
                            State = "PA",
                            Venue = "John F. Kennedy Stadium"
                        },
                        new
                        {
                            Id = 4,
                            City = "New York",
                            FunFact = "A strong late-'80s run at MSG—part of the post-\"Touch of Grey\" resurgence that brought in a new wave of fans.",
                            ShowDate = new DateOnly(1987, 9, 18),
                            State = "NY",
                            Venue = "Madison Square Garden"
                        },
                        new
                        {
                            Id = 5,
                            City = "New York",
                            FunFact = "A classic early-1970 Fillmore East set, showcasing the band as it bridged the psychedelic era into tighter songcraft.",
                            ShowDate = new DateOnly(1970, 2, 13),
                            State = "NY",
                            Venue = "Fillmore East"
                        },
                        new
                        {
                            Id = 6,
                            City = "Chicago",
                            FunFact = "The band's final concert—an emotional capstone to three decades of touring and a major point of reflection in Deadhead history.",
                            ShowDate = new DateOnly(1995, 7, 9),
                            State = "IL",
                            Venue = "Soldier Field"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
